### ISSUE TITLE
Eslint is not recognized as a command 

### ISSUE THREAD

**Issue by simoncheng987** [701-T4/flatshare#103]
**Describe the bug**

eslint is not recognised as an internal and external command see below screenshot, when running command `eslint --fix --max-warnings 0 ` from the terminal

**To Reproduce**

1. pull from the flatshare main repo
2. `yarn install` all the node modules
3. try to do a git commit
4. eslint is not recognised as an internal and external command see below screenshot

**Expected behavior**

eslint should be able to run and fix all the warnings, to make it **TEMPORARILY** work you can use the command `npm i -g eslint` at root. Ultimately this needs to be fixed by adding the dependencies in the root package

**Screenshots**

![image](https://user-images.githubusercontent.com/65271856/158159655-4573a52b-96e9-4ec0-8721-c726ae83a055.png)

**Desktop (please complete the following information):**

 - OS: Windows 10

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by frasermcc9** [comment]
> this can be fixed after running npm i -g eslint at root

Just a note this isn't a proper fix, this installs it globally on your computer. Our repo should not depend on global installs if possible. The proper fix would be to locally install eslint to the repo (i.e. without the -g)

**Comment by simoncheng987** [comment]
> > this can be fixed after running npm i -g eslint at root
> 
> Just a note this isn't a proper fix, this installs it globally on your computer. Our repo should not depend on global installs if possible. The proper fix would be to locally install eslint to the repo (i.e. without the -g)

Thanks Fraser, description updated
