### ISSUE TITLE
Email + password account breaks Profile Icon

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#112]
**Describe the bug**

When you have an email + password account, the profile picture icons break.

**To Reproduce**

1. Create and sign in with email + password
2. Notice that the user icons are broken

**Expected behavior**
1. The lack of profile picture should be handled appropriately, with a default "anonymous" like avatar.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by j-chad** [comment]
cool library I found that might help: https://github.com/nusu/avvvatars
