### ISSUE TITLE
titles don't match up

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#116]
**Describe the bug**
The title of the app doesn't match what is shown on the home screen

**To Reproduce**

1. Go to home screen

**Expected behavior**
Both titles should be "FlatShare"

**Screenshots**
![image](https://user-images.githubusercontent.com/7777317/158888341-1484dc7e-451d-468d-8cb6-5c4dca941803.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 98.0

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by yzhe819** [comment]
I will have a look
