### ISSUE TITLE
(DX) React Code Style

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#12]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to have a common code style in the React application to make the code consistent and more readable.

**Describe the solution you'd like**
A Wiki page outlining the code style of the react side of the app.

The proposed react conventions are written here:
https://github.com/701-T4/platform/wiki/React-Code-Conventions

**Comment by GlockTian** [comment]
@frasermcc9 
 Can you also give a code example of the controller and component working together?

**Comment by frasermcc9** [comment]
> Can you also give a code example of the controller and component working together?

Done

**Comment by GlockTian** [comment]
also, is there a reason for the preference of FC over class component?

**Comment by frasermcc9** [comment]
I'd say class components are basically dead in modern react codebases.

FC are less verbose, easier to read, and encourage more reusable code. The only time I've seen a class component actually being needed is for fairly exotic things like `getDerivedStateFromProps`.
