### ISSUE TITLE
Get bill from id endpoint missing

### ISSUE THREAD

**Issue by GlockTian** [701-T4/flatshare#132]
**Describe the bug**

Currently, there is no endpoint for getting a bill based on id

**Expected behavior**

There should be an endpoint fo getting the bill from bill id

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by j-chad** [comment]
for now we will just use the /bills endpoint and filter by id on the client side. May reopen in the future
