### ISSUE TITLE
Decide on and create projects for 3rd party services (i.e. auth)

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#14]
**Is your feature request related to a problem? Please describe.**
Our application will likely require 3rd party services to handle things that we probably shouldn't (i.e. auth).

**Describe the solution you'd like**
Firebase setup with auth and hosting enabled. Firebase added to the project. Members have access to the firebase project.

**Discussion**
Do we want to use another hosting provider or another auth provider? Firebase auth and hosting will be free for us, and its very easy to use, which is why I've suggested it, but open to new ideas.

**Comment by j-chad** [comment]
auth0 might be a good alternative to firebase
