### ISSUE TITLE
Implement PUT /house/update endpoint

### ISSUE THREAD

**Issue by jimwang6012** [701-T4/flatshare#144]
**Is your feature request related to a problem? Please describe.**

Implement `PUT /api/v1/house/update` endpoint to update house information when the house configuration is changed and saved. 

**Describe the solution you'd like**

- [x] Create a new controller in `house.controller.ts` for the new endpoint
- [x] Update the house schema in `house.schema.ts` to accommodate for the newly added configuration properties
- [x] Update the `GET /api/v1/house` endpoint and DTO to return the newly added configuration properties
- [ ] ~~Change the `update` service in `houseStore.service.ts` to update the new configuration properties in the database (***may not need to***)~~

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by hajineats** [comment]
approved!
