### ISSUE TITLE
Add announcement creation modal 

### ISSUE THREAD

**Issue by hajineats** [701-T4/flatshare#166]
**Is your feature request related to a problem? Please describe.**
This is part of building the new feature called announcement. 

**Describe the solution you'd like**
Need to create a modal that takes title and detail of the new announcement to be made, and when publish is clicked, it should call a callback with result.

<img width="546" alt="Screen Shot 2022-03-31 at 2 45 36 AM" src="https://user-images.githubusercontent.com/68993476/160849332-6e86e980-186b-4ab5-b31c-7c5a7558ddc5.png">

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### Checklist:
- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by jimwang6012** [comment]
Approved!
