### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#17]
## Is your feature request related to a problem? Please describe.

We want new users to be able to see what our app is about before creating an account. There should be a button that can redirect users to the create account page.

## Describe the solution you'd like

- A basic design for the landing page
- That design to be implemented into the frontend
- Buttons (i.e. in a top navbar) that will redirect the user to our signin page.

## Additional Context

Example landing pages:
https://discord.com/
https://www.sushi.com/

Obviously they are not needed to be near as professional as those, that would be more stretch goals. For now, something extremely basic with a title and a navbar up the top with a signup/login button would be acceptable for this to be complete.

**Comment by ywu666** [comment]
Using Figma to design the landing page. The image below shows the landing page tamplate.
<img width="922" alt="image" src="https://user-images.githubusercontent.com/49899381/156950255-468d2663-c1dd-4775-85b3-9fefe1a8b9a0.png">
