### ISSUE TITLE
Issues Wiki Page

### ISSUE THREAD

**Issue by sliu929** [701-T4/flatshare#177]
**Is your feature request related to a problem? Please describe.**

Create the wiki page for the Issues feature

**Describe the solution you'd like**

Follow the formatting for the other wiki pages and describe the specification, front end, and backend

### Checklist:

- [x] Authors
- [x] Specification
- [x] Front-End
- [x] Back-End
- [x] Move from doc to wiki
- [x] Formatting

**Comment by noahjade** [comment]
Documented at: https://github.com/701-T4/flatshare/wiki/Maintenance-Issues-Specification
