### ISSUE TITLE
Ports remain open after sigint

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#20]
**Describe the bug**
After sigint in the start:dev root script, the applications don't properly close. May be a windows issue.

**To Reproduce**
1. Run `start:dev`
2. Ctrl + C to kill
3. Ports are still in use (try to start:dev again)

**Expected behavior**
Killing the script should kill all processes (hence freeing the ports).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows

## Proposed Fix
- Add a script that will just kill the processes on port 3000 and 4200
- Investigate other fixes (i.e. sigint handlers)

**Comment by j-chad** [comment]
Is this the same for react ports?

**Comment by frasermcc9** [comment]
Yeah it doesnt kill either process. I'm guessing a lerna issue.

**Comment by j-chad** [comment]
also for additional context: this does not occur on Ubuntu 20.04 with zsh

**Comment by AbhiRehal** [comment]
So it works fine in Git Bash so we have decided against investing any further time into the issue for now. This has been added as the solution under Troubleshooting.
