### ISSUE TITLE
Generate types for API requests

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#22]
## Is your feature request related to a problem? Please describe.
An easy way to waste time is to wonder why some API calls aren't working as we'd expect. Since we are using swagger (OpenAPI), it would be nice if we could leverage that, alongside typescript, to create type definitions for our API.

## Describe the solution you'd like
Investigate tools that will allow the generation of TypeScript interfaces from swagger documents, [such as this](https://github.com/drwpow/openapi-typescript). These tools will likely want to use the swagger json located at http://localhost:4200/api-json (when the api is running).

If something like this looks promising, then implement an npm script (located in the frontend `package.json`) that will generate a file containing all type definitions for our API. If more complex logic is required, then the npm script can always simply run a single javascript file with the logic implemented in there.

## Acceptance Criteria
If I run a script (for example, `npm run generate`), then a file inside the frontend directory (maybe in `src/typings`) will be generated/updated that has type definitions for our API.

**Comment by j-chad** [comment]
can also integrate with https://github.com/ajaishankar/openapi-typescript-fetch
