### ISSUE TITLE
Add FE authentication

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#31]
## Is your feature request related to a problem? Please describe.
We need to authenticate users to show them the relevant information.

## Acceptance Criteria
- Add firebase to the project FE
- Add a Sign in with google button, possibly using this: (https://www.npmjs.com/package/react-firebaseui)
- There should be a high up React context that stores the user object. 
  - A custom hook like `useAuth()` should give access to the current user, using this context.

## Describe the solution you'd like
Firebase authentication - sign in with google

## Describe alternatives you've considered
Auth0 - Less familiar and would be more effort to setup.
Our own Auth system - Significantly more effort, increases security risk, not as convenient for users.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by frasermcc9** [comment]
@wshe874 I can add firebase to the frontend and then you can set the react specific parts up?

**Comment by wshe874** [comment]
@frasermcc9 Yup sounds good. Should I wait for your PR for adding Firebase merged first?
