### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#41]
## Is your feature request related to a problem? Please describe.
Users need to be able to add and join houses.

## Describe the solution you'd like
Once a user is logged in, they need to be able to create or join a house. Detailed specification for the entire milestone is on [this page](https://github.com/701-T4/platform/wiki/Account-Management-Specification).

For this task, the specs are as follows (not yet final):
### Frontend
- New users will be shown a screen where they can either create or join a house
  - Joining a house will require a code
  - Creating a house will ask the user for some basic information, such as a name
- Users in a house will be directed to the dashboard for that house
  - This task doesn't require the dashboard to be implemented, just that they are redirected to the page

#### Screens
- Page to create new or join house
- Page to create a new flat

### Backend
- New users are created in the database with the Firebase (#40)
  - Please modify the guard to create a new user in the db if the auth is correct but user doesn't exist. See comments on issue #40 and related PR #51 for details
- Endpoint to get the user's current house
- Endpoint to create a new house, owned by the creator.
  - Usable by people who are not in a house
  - The house must have a unique associated code that can be used to join it
- Endpoint to join a house with a code, that will add the user to that house

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by ywu666** [comment]
The design of the account-management page. 
<img width="705" alt="image" src="https://user-images.githubusercontent.com/49899381/157176268-fc1d2e52-a8cd-4519-bca2-964eca93e38f.png">

The UI design about after clicking the create button:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/49899381/157176364-66b77497-9b36-4ab8-9185-8b4090563344.png">
