### ISSUE TITLE
dependency license checking

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#43]
**Is your feature request related to a problem? Please describe.**
We need to check all the licenses of our dependencies to ensure they are compatible with our project

**Describe the solution you'd like**
We need to go through each dependency and check if we are able to use it, and if so are there any conditions to use?
We may have to add an attribution section to our app. Potentially could also attribute in the wiki but unsure

Also should add a check in the PR checklist to add any attribution required

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by j-chad** [comment]
the logo will also need attribution https://thenounproject.com/icon/real-estate-30626/

**Comment by GlockTian** [comment]
https://blog.bitsrc.io/how-i-analyzed-all-npm-dependency-licenses-in-one-go-18de0f7244bc

license-checker for npm module
