### ISSUE TITLE
Improve backend .env handling

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#49]
**Is your feature request related to a problem? Please describe.**
It is frustrating when getting started with the project to manage the environment files. The back-end currently manages the .env files using templates while the front end relies on overriding the default config.

**Describe the solution you'd like**
We should make the back-end use the same logic as the front-end so that the code works by default without any additional config.
Ideally we also move the .env files to the root directory and merge the front-end and back-end env files.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by simoncheng987** [comment]
I wrote temporary solutions in [trouble shooting](https://github.com/701-T4/platform/wiki/Trouble-Shooting#database-fail-to-connect), you might find this useful.

**Comment by frasermcc9** [comment]
They can't be handled the same way as FE since BE env will contain secrets

**Comment by frasermcc9** [comment]
Possibly one solution is a simple script that runs at startup that will compare the devs .env to the sample one and output friendly errors if they are missing any

**Comment by j-chad** [comment]
Also maybe a yarn script that you can run to do initial setup
