### ISSUE TITLE
Design and Build Login Page

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#62]
**Is your feature request related to a problem? Please describe.**
Right now the login page is just blank with a sign in button. We should try to make it look nicer.

**Describe the solution you'd like**
Implement an actual login page.

**Additional context**
Potential design ideas:
![image](https://user-images.githubusercontent.com/55963097/157599171-726a1a0d-5aa6-4c44-a87d-4f8de5ae51b6.png)
![image](https://user-images.githubusercontent.com/55963097/157599104-5218068d-edaa-44a9-8669-8f3c6ce48859.png)
![image](https://user-images.githubusercontent.com/55963097/157599231-e1567987-faf5-414e-b15f-f1ea4d3c6b94.png)

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by GlockTian** [comment]
have we enabled email sign-in opion in the firebase console?

**Comment by frasermcc9** [comment]
> have we enabled email sign-in opion in the firebase console?

We only are doing Google login currently,

**Comment by GlockTian** [comment]
Should I still make the Email + password field there, and leave it for future development?

**Comment by frasermcc9** [comment]
The images are just rough ideas of what it might look like, but for now the only button should be the google sign in
