### ISSUE TITLE
spike: 3rd party mongodb hosting

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#64]
**Is your feature request related to a problem? Please describe.**
It is frustrating to have to install mongodb before being able to run the app or do any work. We should have some way for developers to be able to get started without having to install anything.

**Describe the solution you'd like**
Ideally we can find some free online hosting for mongodb. 

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by kaylward** [comment]
@j-chad what do you think about doing something like this https://mkyong.com/mongodb/how-to-install-mongodb-on-windows/ and use a script?

**Comment by j-chad** [comment]
> @j-chad what do you think about doing something like this https://mkyong.com/mongodb/how-to-install-mongodb-on-windows/ and use a script?

yes thats what we're currently doing

**Comment by j-chad** [comment]
we have decided to leave this for now
