### ISSUE TITLE
add logout route

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#76]
**Is your feature request related to a problem? Please describe.**
There is currently no way to logout on the frontend.

**Describe the solution you'd like**
there should be a route `/logout` that removes the token from the cache. Links to the logout screen should be added when appropriate.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by fishmonger45** [comment]
I'd like to try this

**Comment by j-chad** [comment]
we should leave this to the @701-T4/front-end team

**Comment by j-chad** [comment]
contained in #72
