### ISSUE TITLE
GET /api/v1/house should return 404 if user doesn't have a house

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#77]
**Describe the bug**
Currently the endpoint `/api/v1/house` returns an empty body if the user doesn't have a house assigned. Instead we should return 404 status.

**To Reproduce**

1. call `/api/v1/house` with a user that doesn't have a house assigned
2. the body will be empty

**Expected behavior**
http 404 should be returned

**Additional context**

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by frasermcc9** [comment]
Would prefer for getting the house not to 404.

The user not having a house is an expected result and it may be more appropriate (and easier to work with on the frontend) if it returned something like a 204.
