### ISSUE TITLE
Ping Endpoint

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#8]
**Is your feature request related to a problem? Please describe.**
We need to develop a base for our back-end infrastructure.

**Describe the solution you'd like**
A ping endpoint lets us get the initial development done so we can expand later. It will also be used by front-end to verify setup.
It should simply respond with the current time (JSON format).

**Describe alternatives you've considered**
I cannot think of any endpoints that would be constructive to the final product at this point in time.

**Comment by frasermcc9** [comment]
Can I add loading a .env file (prerably .env.development and .env.production based on NODE_ENV) as an acceptance criteria?

[env in nest](https://docs.nestjs.com/techniques/configuration)

**Comment by j-chad** [comment]
AC?

**Comment by frasermcc9** [comment]
acceptance criteria

**Comment by j-chad** [comment]
ah yep go for it
