### ISSUE TITLE
Backend - Add bill splitting endpoints

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#80]
Bill splitting is an essential part of a flat sharing application and is the backbone of this app. Users should be able to create and share bills with their flatmates.

### Specification
* User can add bills to a flat.
  * The user who makes the bill is the owner.
  * Should have a description of what it is for and how to pay.
  * Upload pdf option.
  * Bills have due dates (will be sorted by due date).
  * Add users from the flat to bill.
  * Enter manually the number to be paid from each user.
    * Shortcuts to split bill evenly.
* Users can mark bills as paid. Will show on the bill which users have paid.
  * Optionally the user can upload proof (as image).
  * Can unmark as paid if accidentally marked as paid.
* ~~Save a bill as a template.~~
  * ~~Templates can be loaded quickly when creating new bill.~~

### Back-End Specification
* Introduce new bills table with the following columns:
  * Name,
  * Description,
  * Owner,
  * Due,
  * Users,
    * id,
    * amount,
    * paid (boolean),
    * proof (blob storage id)
* Proof should be able to be accessed from blob storage.
  * https://firebase.google.com/products/storage.
* Add endpoints:
    * GET /house/bills
      * Retrieve all bills in the users flat.
      * Bills Ordered first ordered by not paid first then paid.
        * Then ordered by the due date (most urgent at top).
      * Response structure should be the same as db structure.
    * POST /house/bills
      * Create a new bill.
    * PUT /house/bills/{id}
      * Update a bill.
      * Ensure requestor is the owner.
      * Can only update name and description.
    * PUT /house/bills/{id}/payment
      * Mark a user as having paid or unpaid a bill.
      * Optionally, can include proof ID
    * DELETE /house/bills/{id}
      * Delete a bill.
      * Ensure requestor is the owner.
    * ~~GET /house/users~~
      * ~~Return all users in the house~~

## Considering a bill paid
* If the user is the owner then the bill is considered paid if all users have paid. Otherwise it is unpaid.
* If the user is **not** the owner, then the bill is considered paid if that specific user has paid. Otherwise it is unpaid

## Sample Bill Response
```json
{
  "id": "ObjectID",
  "name": "string",
  "description": "string",
  "owner": "FirebaseID",
  "due": 23424223,
  "users": [
    {
      "id": "FirebaseID",
      "amount": 23.00,
      "paid": false,
      "proof": "BlobID" //Optional, should get from front-end
    }
  ]
}
```

**Additional context**

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by oscarli00** [comment]
Is it ok to have the retrieve all bills endpoint as GET /house/bills instead? Seems to make more sense that way

**Comment by j-chad** [comment]
yes, sorry that was a typo. I have updated it to `GET /house/bills`

**Comment by GlockTian** [comment]
{
    "id": "string",
    "name": "string",
    "description": "string",
    "owner": "firebaseID",
    "due": 1647215067300,
    "users": [
        {
            "id": "firebaseId",
            "amount": 30, //$
            "paid": false,
            "proof": "blob id" //optional
        },
        ...
    ]
}


Can we store due date as a string instead of that integer?
