### ISSUE TITLE
Backend - add task splitting endpoints

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#81]
## Specification
* Users can create tasks and assign them to any user.
  * Tasks can be edited by anyone.
  * Can be assigned randomly or fixed.
  * Can be recurring.
    * Done state is reset on a given frequency.
    * If randomly assigned, pick a new user.
* Users can mark tasks they are assigned to as done.
* Users can delete tasks.

## Back-End
* Introduce new “tasks” table with the following structure:
  * name,
  * description,
  * last_completed (optional, time),
  * due_date,
  * interval (optional, in seconds),
  * assigned (user id),
  * pool (optional, user id array)
* User Pool - random user from pool will be assigned to task.
* Recurrence Rules:
  * Recurrence should be checked whenever a task is queried before it is returned.
  * If the current time is past due_date + interval:
    * Set to incomplete (delete last_completed column).
    * Set due date to (due_date + interval).
      * If this is in the past increase by interval until the future.
    * Reassign from user pool, if needed.
* Endpoints
  * GET /house/tasks
    * Return all active tasks in the house.
  * GET /user/tasks
    * Return all active tasks assigned to user.
  * POST /house/tasks
    * Create a new task.
  * PUT /house/task/{id}
    * Ensure requestor is the owner.
    * Modify task name, description or pool.
    * If assigned user is no longer in pool choose a new assigned user.
  * PUT /house/task/{id}/completed
    * Mark a user as having completed (or not) a task.
    * User must be assigned.
  * DELETE /house/task/{id}
    * Delete a task.
    * User must be owner.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by mped822** [comment]
oops my bad i accidentally clicked a button
