### ISSUE TITLE
Frontend - Bill Splitting

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#83]
**Is your feature request related to a problem? Please describe.**
Bill splitting is a core feature of the application.

**Describe the solution you'd like**

## These are the specifications, ask for any clarifications

* Add a new PRIVATE page - /bills.
  * Add to private page router.
  * Dashboard: bill splitting card to navigate to bill splitting page.
  * Should list bills:
    * Bills ordered first by not paid, then paid after.
    * Then ordered by the due date (most urgent at top).
    * Suggestion: make design similar to the “upcoming” cards on the dashboard page, but ultimately up to implementers.
    * This card should show the bill name, description, cost.
  * People can click a bill to open a details page.
    * This page should be on /bills/{id} - to implement this and for getting path params, look at the react router.
    * There the user can upload proof (pdf or image).
    * This will be uploaded to [here](https://firebase.google.com/docs/storage/web/upload-files).
    * Generate a uuidv4 string (npm uuid), name the file that, send the generated link to the backend.
    * The details page should also name the bill, show description, cost etc.
    * There should be a button (i.e. a toggle) to indicate it is paid.
      * You do not need to upload a bill in order to select this toggle.
    * The OWNER of the task should be able to edit parameters, such as the description, name.
  * Go back to the dashboard button.
  * At the top of the page there should be an option to create a new bill
    * This can be modal:
      * Bill name.
      * Description.
      * Due date.
      * Total cost.
      * Option for splitting bill evenly (default on)
      * If unchecked, show a table of all the people in the house, the user can enter specific quantities for each user to pay.
  * Also ensure a go back to dashboard option at the top that navigates back to the dashboard.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by Sparye** [comment]
Do we need a description for the bill modal? Bill name, total cost and due date pretty much cover everything a bill should specifiy

**Comment by GlockTian** [comment]
Is the Toggle indicated 

- [ ] whether the single individual has paid？

- [ ] or the entire bill?

**Comment by frasermcc9** [comment]
The toggle is per user. Once every user in the flat has paid, the bill is considered complete.

**Comment by GlockTian** [comment]
I would also need A local file picker like this?
https://www.npmjs.com/package/use-file-picker
