### ISSUE TITLE
Backend - get users in a flat

### ISSUE THREAD

**Issue by j-chad** [701-T4/flatshare#84]
**Is your feature request related to a problem? Please describe.**
currently we do not have a way to get all of the users in a house

**Describe the solution you'd like**
update endpoint `GET /house` so it also return `users` which is an array of UserResponseDTO
update endpoint `PUT /house` so it assigns the user to another house 

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by oscarli00** [comment]
Seems to be a copy of GET /house/users from #80. Is it ok to remove that from the back end specification in #80? Or have that implemented as part of this issue.

**Comment by j-chad** [comment]
yes please
