### ISSUE TITLE
Consolidate and Organize Documentation

### ISSUE THREAD

**Issue by frasermcc9** [701-T4/flatshare#92]
**Is your feature request related to a problem? Please describe.**
Our current documentation is either missing information, contradictory or confusing.

**Describe the solution you'd like**
Clearly organize our documentation on how to run the project.

- [x] Update README
- [x] Update CONTRIBUTING
- [ ] Update wiki 

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

**Comment by j-chad** [comment]
Am I ok to close this issue now?

**Comment by noahjade** [comment]
Closing as the project has been handed off to new team, and project wiki was updated before that.
